version: "3.8"
services:
  web:
    build:
      context: ./app
    image: py313-flask-app:latest
    container_name: mstg-proposal-app-container
    restart: unless-stopped
    expose: ["5000"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/healthz"]
      interval: 15s
      timeout: 3s
      retries: 5

  nginx:
    build:
      context: ./nginx
    image: py313-nginx-proxy:latest
    container_name: nginx-reverse-proxy
    restart: unless-stopped
    depends_on:
      web:
        condition: service_healthy
    ports:
      - "443:443"
    volumes:
      - ./certs:/etc/nginx/certs:ro

networks:
  default:
    name: proposal_writer_agent_default

