version: "3.8"
services:
  web:
    build:
      context: ./app
    env_file: .env
    image: mkprasad/proposal-app:latest
    container_name: mstg-proposal-app-container
    restart: unless-stopped
    expose: ["5000"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/healthz"]
      interval: 15s
      timeout: 3s
      retries: 5
    environment:
      INPUT_FILES_FOLDER: input_data   # relative to app root, resolves to /app/input_data
      DOWNLOAD_FOLDER: generated_proposals  # relative to app root, resolves to /app/generated_proposals

  nginx:
    build:
      context: ./nginx
    image: mkprasad/proposal-nginx:latest
    container_name: nginx-reverse-proxy
    restart: unless-stopped
    depends_on:
      web:
        condition: service_healthy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./certs:/etc/nginx/certs:ro

networks:
  default:
    name: proposal_writer_agent_default

